### ISSUE TITLE
what is the purpose of this program?

### ISSUE THREAD

**Issue by sewnie** [D3vil0per/catana#2]
this program by itself has ton's of scripting failures and generally bad code, i hope this is your program.

why does this program need to be its whole new program? whats wrong with using a 1 command AWK and sed/grep with regex??

**Comment by D3vil0p3r** [comment]
> 

Hello @wael444 please tell me which errors/failures you get and which environment you are running on, I'll try to go in. For the main question: it is pretty clear the purpose of this program on the README.md. And a big number of (also famous) tools can be subsituted by 1 single line of AWK/SED/grep commands, but we love to make spicy menus and spamming grep commands.

PS: if you wish, you can create a pull request for improving the code.

**Comment by sewnie** [comment]
just realized this is script for... yeah sorry for wasting your time.
